[global_data]
# Size of the matrix to use
n = 6
# Options: 
#  - niep, for stochastic niep;
#  - sniep, for stochasic sniep;
#  - sub_sniep, for substochastic sniep.
matrix_type = "sniep" 
# Number of sampled points for each axis.
points_dim = [11,11,11,11]
funcs_to_optimize = [2, 3, 4,5]

[optimize_data]
tol = 1e-7
maxiter = 100000
attempts = 1000

[file_utils_data]
# Sets the percision to round the data when it is saved.
decimal_precision = 3

[plot_data]
num_eigenvalue_slices = 5
slice_tolerance = 0.05