[global_data]
# Size of the matrix to use
n = 6
# Options: 
#  - niep, for stochastic niep;
#  - sniep, for stochasic sniep;
#  - sub_sniep, for substochastic sniep.
matrix_type = "niep" 
# Number of sampled points for each axis.
points_dim = [37,37,37]
funcs_to_optimize = [2, 3, 4]

[optimize_data]
attempts_slsqp = 20
attempts_trust = 20
log_success_every_n = 2000
maxiter = 10000
optimizer_rounding = 4
tol_nlc = 1e-2
tol_slsqp = 1e-7
tol_trust = 1e-5

[file_utils_data]
# Sets the percision to round the data when it is saved.
decimal_precision = 3

[plot_data]
num_eigenvalue_slices = 5
slice_tolerance = 0.05