[global_data]
# Size of the matrix to use
n = 6
# Options: 
#  - niep, for stochastic niep;
#  - sniep, for stochasic sniep;
#  - sub_sniep, for substochastic sniep.
matrix_type = "sub_sniep" 
# Number of sampled points for each axis.
points_dim = [11,11,11,11]
funcs_to_optimize = [2, 3, 4,5]
plot_with_optimize = true

[optimize_data]
attempts_slsqp = 20
attempts_trust = 20
log_every_n = 2000
maxiter = 10000
optimizer_rounding = 4
tol_nlc = 1e-2
tol_slsqp = 1e-7
tol_trust = 1e-5

[file_utils_data]
# Sets the percision to round the data when it is saved.
decimal_precision = 3

[plot_data]
plot_tolerance = 1e-3
num_animation_frames = 5
data_location = ""

[extreme_points_data]
use_permutations = false
points_to_check_path = ""
num_furthest_points = 5
tolerance = 1e-5
hull_points_path = "extreme_points/point_sets.json"
hull_points_set_name = ""
external_points_output_path = "extreme_points/points_outside_hull.json"
