# -*- coding: utf-8 -*-
# Symbolic Functions for N = 3 (General Symm. Stochastic)
# Generated by script

import math
import numpy as np


# --------------------------------------------------------------------------
# Value Function (S1_n3)
# Input: x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
# --------------------------------------------------------------------------
def calculate_S1_n3(x_vec):
    """Calculates S_1 for n=3 general symm. stochastic matrix.
    Args:
        x_vec (numpy array or list/tuple): Input vector of length 6
           containing the strict upper triangle elements in row-wise order:
                      x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
           Diagonal elements are determined by stochastic constraint.
    
    Returns: float: S_1 value.
    """
    # Assign vars
    x_0_0 = x_vec[0]
    x_0_1 = x_vec[1]
    x_0_2 = x_vec[2]
    x_1_1 = x_vec[3]
    x_1_2 = x_vec[4]
    x_2_2 = x_vec[5]
    # S_k CSE Defs

    # Final S_k Calculation
    result = x_0_0 + x_1_1 + x_2_2
    return result



# --------------------------------------------------------------------------
# Jacobian Function (S1_n3)
# Input: x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
# --------------------------------------------------------------------------
def calculate_S1_n3_jacobian(x_vec):
    """Calculates Jacobian of S_1 (n=3).
    Args:
        x_vec (numpy array or list/tuple): Input vector of length 6
           containing the strict upper triangle elements in row-wise order:
                      x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
           Diagonal elements are determined by stochastic constraint.
    
    Returns: list: Gradient vector.
    """
    # Assign vars
    x_0_0 = x_vec[0]
    x_0_1 = x_vec[1]
    x_0_2 = x_vec[2]
    x_1_1 = x_vec[3]
    x_1_2 = x_vec[4]
    x_2_2 = x_vec[5]
    # Jacobian CSE Defs

    # Final Gradient Calculation
    gradient = [
        1,
        0,
        0,
        1,
        0,
        1
    ]
    return gradient



# --------------------------------------------------------------------------
# Value Function (S2_n3)
# Input: x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
# --------------------------------------------------------------------------
def calculate_S2_n3(x_vec):
    """Calculates S_2 for n=3 general symm. stochastic matrix.
    Args:
        x_vec (numpy array or list/tuple): Input vector of length 6
           containing the strict upper triangle elements in row-wise order:
                      x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
           Diagonal elements are determined by stochastic constraint.
    
    Returns: float: S_2 value.
    """
    # Assign vars
    x_0_0 = x_vec[0]
    x_0_1 = x_vec[1]
    x_0_2 = x_vec[2]
    x_1_1 = x_vec[3]
    x_1_2 = x_vec[4]
    x_2_2 = x_vec[5]
    # S_k CSE Defs

    # Final S_k Calculation
    result = x_0_0*x_1_1 + x_0_0*x_2_2 - x_0_1**2 - x_0_2**2 + x_1_1*x_2_2 - x_1_2**2
    return result



# --------------------------------------------------------------------------
# Jacobian Function (S2_n3)
# Input: x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
# --------------------------------------------------------------------------
def calculate_S2_n3_jacobian(x_vec):
    """Calculates Jacobian of S_2 (n=3).
    Args:
        x_vec (numpy array or list/tuple): Input vector of length 6
           containing the strict upper triangle elements in row-wise order:
                      x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
           Diagonal elements are determined by stochastic constraint.
    
    Returns: list: Gradient vector.
    """
    # Assign vars
    x_0_0 = x_vec[0]
    x_0_1 = x_vec[1]
    x_0_2 = x_vec[2]
    x_1_1 = x_vec[3]
    x_1_2 = x_vec[4]
    x_2_2 = x_vec[5]
    # Jacobian CSE Defs

    # Final Gradient Calculation
    gradient = [
        x_1_1 + x_2_2,
        -2*x_0_1,
        -2*x_0_2,
        x_0_0 + x_2_2,
        -2*x_1_2,
        x_0_0 + x_1_1
    ]
    return gradient



# --------------------------------------------------------------------------
# Value Function (S3_n3)
# Input: x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
# --------------------------------------------------------------------------
def calculate_S3_n3(x_vec):
    """Calculates S_3 for n=3 general symm. stochastic matrix.
    Args:
        x_vec (numpy array or list/tuple): Input vector of length 6
           containing the strict upper triangle elements in row-wise order:
                      x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
           Diagonal elements are determined by stochastic constraint.
    
    Returns: float: S_3 value.
    """
    # Assign vars
    x_0_0 = x_vec[0]
    x_0_1 = x_vec[1]
    x_0_2 = x_vec[2]
    x_1_1 = x_vec[3]
    x_1_2 = x_vec[4]
    x_2_2 = x_vec[5]
    # S_k CSE Defs

    # Final S_k Calculation
    result = x_0_0*x_1_1*x_2_2 - x_0_0*x_1_2**2 - x_0_1**2*x_2_2 + 2*x_0_1*x_0_2*x_1_2 - x_0_2**2*x_1_1
    return result



# --------------------------------------------------------------------------
# Jacobian Function (S3_n3)
# Input: x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
# --------------------------------------------------------------------------
def calculate_S3_n3_jacobian(x_vec):
    """Calculates Jacobian of S_3 (n=3).
    Args:
        x_vec (numpy array or list/tuple): Input vector of length 6
           containing the strict upper triangle elements in row-wise order:
                      x_0_0, x_0_1, x_0_2, x_1_1, x_1_2, x_2_2
           Diagonal elements are determined by stochastic constraint.
    
    Returns: list: Gradient vector.
    """
    # Assign vars
    x_0_0 = x_vec[0]
    x_0_1 = x_vec[1]
    x_0_2 = x_vec[2]
    x_1_1 = x_vec[3]
    x_1_2 = x_vec[4]
    x_2_2 = x_vec[5]
    # Jacobian CSE Defs

    # Final Gradient Calculation
    gradient = [
        x_1_1*x_2_2 - x_1_2**2,
        2*(-x_0_1*x_2_2 + x_0_2*x_1_2),
        2*(x_0_1*x_1_2 - x_0_2*x_1_1),
        x_0_0*x_2_2 - x_0_2**2,
        2*(-x_0_0*x_1_2 + x_0_1*x_0_2),
        x_0_0*x_1_1 - x_0_1**2
    ]
    return gradient


