# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_block.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_block.proto\"T\n\tDataBlock\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0c\x63oefficients\x18\x02 \x03(\x01\x12\x0e\n\x06matrix\x18\x03 \x03(\x01\x12\x13\n\x0b\x65igenvalues\x18\x04 \x03(\x01\"+\n\x0e\x44\x61taBlockArray\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.DataBlockb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_block_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATABLOCK._serialized_start=20
  _DATABLOCK._serialized_end=104
  _DATABLOCKARRAY._serialized_start=106
  _DATABLOCKARRAY._serialized_end=149
# @@protoc_insertion_point(module_scope)
